### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by kruug** [greyscalepress/manifestos#19]
Attempting to build on Debian, missing "HKGrotesk-Regular" and "LinLibertineOB" for sure.  Still looking for a place to download "LinLibertineOB" and then will be able to tell if more fonts are missing.  May want to include them as part of the build.sh script or at least include them in a directory.

**Comment by kruug** [comment]
Also font "Futura"

**Comment by ms-studio** [comment]
Indeed, I will include a folder with the currently used fonts. 

In the meantime, here is where you can get them: 

Linux Libertine: https://sourceforge.net/projects/linuxlibertine/

HK Grotesk: https://fontlibrary.org/en/font/hk-grotesk

**Comment by ms-studio** [comment]
And btw, Futura isn't actually used – the `sansfont` and `monofont` variables in the `build.sh` script are not used, they are simply a leftover of some Pandoc sample code. Even the `bolditalicfont` isn't used anywhere in the book.

**Comment by ms-studio** [comment]
Added fonts with commit 7e48c83
