### ISSUE TITLE
Build script (on macOS) folder and fontname issues

### ISSUE THREAD

**Issue by luistoledo** [greyscalepress/manifestos#31]
On macOS, executing the **build.sh** script fails in three ways:

1. temp directory
```
build.sh: line 48: ../temp/newfile.txt: No such file or directory
pandoc: ../temp/newfile.txt: openFile: does not exist (No such file or directory)
```
Fixed by creating an empty temp directory

2. output directory
```
pandoc: ../output/Manifestos_for_the_Internet_Age-20170607_111323Z.pdf: openBinaryFile: does not exist (No such file or directory)
```
Fixed by creating an empty output directory

3. font name
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "HK Grotesk Pro" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.76      ]{HK Grotesk Pro}

pandoc: Error producing PDF
```
Fixed by changing the font name at line 67, from "HK Grotesk Pro" to "HK Grotesk"

```
--variable mainfont="HK Grotesk" \
```

Solution:

- The first and second issue can be avoided by the same script, checking and creating the folder before the execution.
- For the third one, either change the script file or upload the exact font file
- Also the font installation can be automatized by copy the font files into the /Library/Fonts folder

**Comment by gingerbeardman** [comment]
Fixed in #39
