### ISSUE TITLE
[request] Add support for build .epub 

### ISSUE THREAD

**Issue by luistoledo** [greyscalepress/manifestos#33]
Trying to build an epub file, found these requirements:

- Duplicate the custom.epub to customV2.epub to support modern pandoc versions
- Add a parameter to the build script to change output file extension to .epub

**Comment by ms-studio** [comment]
Great suggestion, having an epub output would be a good thing. 

I think we could have a different build script for the epub format?

**Comment by gingerbeardman** [comment]
pandoc can produce epub

So I added this in #39

**Comment by gingerbeardman** [comment]
This can be closed, fixed in #39 and #42

**Comment by ms-studio** [comment]
Ok, then I'm closing it :)

Thanks a lot for documenting your findings and improvements ! 🙏

**Comment by gingerbeardman** [comment]
@ms-studio my pleasure, don't forget to merge #42
