### ISSUE TITLE
Wireless Commons Manifesto

### ISSUE THREAD

**Issue by adamshand** [greyscalepress/manifestos#43]
I was interested to see that you included a manifesto I instigated and helped write many years ago!  Neat. :-)

If it is possible I would appreciate if you could make two updates to the copy of the document you have here in Github.

1. Could you remove Jon Lebkowsky from the bottom of the document?  He kindly signed the manifesto and forwarded to his network of people but didn't participate in creating it.

2. Could you please add a link to the copy I've preserved which includes the definition of a wireless commons and the list of original signatories.  Suggested text below:

```
NOTE: A copy of the original manifesto (plus the definition and signatories which were
      released at the same time) is preserved at: https://adam.nz/wireless-commons/
```

Cheers,
Adam.

**Comment by ms-studio** [comment]
Hi Adam, thanks a lot for your input. 

I added those changes with commit [1d49f8e](https://github.com/greyscalepress/manifestos/commit/1d49f8e64882b6c033aa110d793ac35898849aa0)

Best,
Manuel

**Comment by adamshand** [comment]
Thank you, much appreciated!

And thanks for the interesting project and the blast from the past.   I have some manifesto's to read! :-)
