### ISSUE TITLE
Add "User Rights" manifesto by Olia Lialina

### ISSUE THREAD

**Issue by ms-studio** [greyscalepress/manifestos#6]
As suggested by Olia Lialina : https://twitter.com/gifmodel/status/672747158152564738

> I suggest to include User Rights to the next edition! … http://userrights.contemporary-home-computing.org/

**Comment by xuv** [comment]
A similar one: https://userdatamanifesto.org/

**Comment by ms-studio** [comment]
@xuv thanks! actually the User Data Manifesto is already included in v.5, released September 2015.

**Comment by xuv** [comment]
Ha. Ok. I guess I have the v.4 then :)

**Comment by ms-studio** [comment]
The "User Rights" manifesto has been included in the meantime.
