### ISSUE TITLE
Suggested missing 'manifestos'

### ISSUE THREAD

**Issue by bramcrevits** [greyscalepress/manifestos#8]
- Xenofeminism Manifesto: http://www.laboriacuboniks.net/
- A Cyborg Manifesto: https://en.wikipedia.org/wiki/A_Cyborg_Manifesto
- A Hacker Manifesto: https://en.wikipedia.org/wiki/A_Hacker_Manifesto
- We lost (or r.i.p.) : http://fffff.at/we-lost/

**Comment by ms-studio** [comment]
Awesome, thanks for those proposals.

The full text of the _Cyborg Manifesto_ and _Hacker Manifesto_ is actually a bit long, more "fully featured essay"-length than "manifesto-length". Would you have a proposal for a suitable excerpt of any of those two?

**Comment by bramcrevits** [comment]
The pleasure is mine. Nice project, by the way. 
The two you refer to are indeed more something like a book than a typical manifesto.. and I don't have a suggestion for an excerpt. Maybe you could do an open call for suggestions on social media, and including the authors in that call?

**Comment by ms-studio** [comment]
Two of the texts - Xenofeminism and We lost - are included in the newest edition: http://www.amazon.com/Manifestos-Internet-Age-Various/dp/2940561028/

**Comment by syntacticalChaos** [comment]
cyberfeminist manifesto for the 21st century (http://www.vnsmatrix.net/)
bitchmutant manifesto (on old boy's network)

by vns matrix

**Comment by violetforest** [comment]
http://cybertwee.net/the_manifesto/

**Comment by ms-studio** [comment]
@syntacticalChaos thanks! I had envisioned adding them from the beginning. Including now the "cyberfeminist manifesto for the 21st century".

**Comment by ms-studio** [comment]
@violetforest thanks for that link, wasn't aware of it! Can you give me slightly more context? Is october 2014 the official publication date? UPDATE: googling a bit gives me the answers, there's a lot of press coverage :)

**Comment by syntacticalChaos** [comment]
@ms-studio excellent to be in such fine company with our ectogenetic offspring/siblings/slime sisters!

**Comment by alexcohen238** [comment]
may i suggest the gender nihilist anti-manifesto? https://libcom.org/library/gender-nihilism-anti-manifesto

**Comment by metamodernist** [comment]
Metamodernist Manifesto (2011): http://www.metamodernism.org/

**Comment by ms-studio** [comment]
@metamodernist thanks for the link! Subjectively I believe the Metamodernist Manifesto falls off the thematic grid of this collection, which is gathering texts embedded in cyber / internet / computer culture. I'm not including texts that are foremost literary / economical / societal / philosophical manifestos. But good to have that reference!

**Comment by metamodernist** [comment]
@ms-studio no probs – it was actually originally written foremost as an internet-culture-led/philosophical manifesto, as that's my background (rather than anything literary theory-based), but it's been picked up in those other spheres too, so I guess its scope is pretty broad :)

**Comment by violetforest** [comment]
@ms-studio yes that is the date! do you have any other questions in regards to the manifesto // our collective? feel free to join our facebook group https://www.facebook.com/groups/364238813738395/

**Comment by ms-studio** [comment]
Closing this, please open new issues for future proposals.
